Repository ori-on1/Explore-Unexplored-Nepal, pull requests merged in 2024-10, with the labels that each got.

#4 Update Data.json
  Data.json
Labels: enhancement

#5 merged
  .gitignore
  Data.json
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/components/Filter.jsx
  src/components/LocationList.jsx
  src/components/Navbar.jsx
  src/components/ProductCard.jsx
  src/components/ProductList.jsx
  src/data/exploreNepalData.js
  src/index.css
  src/main.jsx
  src/utils/getCategoryImage.jsx
  vite.config.js
Labels: enhancement

#10 Siddhababa
  src/data/exploreNepalData.js
Labels: good first issue, hacktoberfest-accepted

#11 Banbatika added
  src/data/exploreNepalData.js
Labels: hacktoberfest-accepted

#12 kunjalapark added
  src/data/exploreNepalData.js
Labels: hacktoberfest-accepted

#13 Peace park is added
  src/data/exploreNepalData.js
Labels: hacktoberfest-accepted
